In [ ]:
#1. อ่านข้อมูลดูภาพรวมข้อมูลสุขภาพจิต
import os
import pandas as pd

# กำหนดที่อยู่ไฟล์
BASE = r"C:\Users\LENOVO\OneDrive - BUU\Desktop\Data"
INPUT_FILE = os.path.join(BASE, "raw", "1- mental-illnesses-prevalence.csv.csv")

# โหลดและเช็กขนาดข้อมูล
if os.path.exists(INPUT_FILE):
    df_mental = pd.read_csv(INPUT_FILE)
    print("=== โหลดไฟล์ mental-illnesses-prevalence.csv สำเร็จ ===")
    print(f"จำนวนแถวและคอลัมน์: {df_mental.shape}")
    display(df_mental.head())
else:
    print(f"ไม่พบไฟล์ที่: {INPUT_FILE}")
    print("ไฟล์ที่มีในโฟลเดอร์ raw:", os.listdir(os.path.join(BASE, "raw")))

=== โหลดไฟล์ mental-illnesses-prevalence.csv สำเร็จ ===
จำนวนแถวและคอลัมน์: (6420, 8)

,Entity,Code,Year,Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized,Depressive disorders (share of population) - Sex: Both - Age: Age-standardized,Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized,Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized,Eating disorders (share of population) - Sex: Both - Age: Age-standardized
0,Afghanistan,AFG,1990,0.223206,4.996118,4.713314,0.703023,0.127700
1,Afghanistan,AFG,1991,0.222454,4.989290,4.702100,0.702069,0.123256
2,Afghanistan,AFG,1992,0.221751,4.981346,4.683743,0.700792,0.118844
3,Afghanistan,AFG,1993,0.220987,4.976958,4.673549,0.700087,0.115089
4,Afghanistan,AFG,1994,0.220183,4.977782,4.670810,0.699898,0.111815

In [ ]:
#1.1 อ่านข้อมูลดูภาพรวมข้อมูลรายได้ประเทศ
import os
import pandas as pd

# กำหนดที่อยู่ไฟล์ income.xlsx
BASE = r"C:\Users\LENOVO\OneDrive - BUU\Desktop\Data"
INCOME_FILE = os.path.join(BASE, "processed", "income.xlsx")

# โหลดและเช็กขนาดข้อมูล
if os.path.exists(INCOME_FILE):
    df_income = pd.read_excel(INCOME_FILE, header=2)
    print("=== โหลดไฟล์ income.xlsx สำเร็จ ===")
    print(f"จำนวนแถวทั้งหมด: {df_income.shape[0]} แถว")
    print(f"จำนวนคอลัมน์ทั้งหมด: {df_income.shape[1]} คอลัมน์")
    print("ขนาดข้อมูล (แถว, คอลัมน์):", df_income.shape)
    display(df_income.head())
else:
    print(f"ไม่พบไฟล์ที่: {INCOME_FILE}")

=== โหลดไฟล์ income.xlsx สำเร็จ ===
จำนวนแถวทั้งหมด: 217 แถว
จำนวนคอลัมน์ทั้งหมด: 32 คอลัมน์
ขนาดข้อมูล (แถว, คอลัมน์): (217, 32)

,AFG,Afghanistan,L,L.1,L.2,L.3,L.4,L.5,L.6,L.7,...,L.20,L.21,L.22,L.23,L.24,L.25,L.26,L.27,L.28,L.29
0,ALB,Albania,LM,LM,LM,L,L,L,LM,L,...,UM,LM,UM,UM,UM,UM,UM,UM,UM,UM
1,DZA,Algeria,LM,LM,LM,LM,LM,LM,LM,LM,...,UM,UM,UM,UM,UM,UM,UM,UM,UM,LM
2,ASM,American Samoa,UM,UM,UM,UM,UM,UM,UM,UM,...,UM,UM,UM,UM,UM,UM,UM,UM,UM,UM
3,AND,Andorra,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
4,AGO,Angola,LM,LM,LM,LM,LM,L,L,L,...,LM,UM,UM,UM,UM,UM,LM,LM,LM,LM

In [ ]:
#2. ตรวจภาพรวมและชนิดข้อมูล
print("ขนาดข้อมูล (แถว, คอลัมน์):", df.shape)
df.info()
print(df.head())

ขนาดข้อมูล (แถว, คอลัมน์): (6420, 8)
<class 'pandas.DataFrame'>
RangeIndex: 6420 entries, 0 to 6419
Data columns (total 8 columns):
 #   Column                                                                             Non-Null Count  Dtype
---  ------                                                                             --------------  -----
 0   Entity                                                                             6420 non-null   str
 1   Code                                                                               6150 non-null   str
 2   Year                                                                               6420 non-null   int64
 3   Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized  6420 non-null   float64
 4   Depressive disorders (share of population) - Sex: Both - Age: Age-standardized     6420 non-null   float64
 5   Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized        6420 non-null   float64
 6   Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized        6420 non-null   float64
 7   Eating disorders (share of population) - Sex: Both - Age: Age-standardized         6420 non-null   float64
dtypes: float64(5), int64(1), str(2)
memory usage: 401.4 KB
        Entity Code  Year  \
0  Afghanistan  AFG  1990
1  Afghanistan  AFG  1991
2  Afghanistan  AFG  1992
3  Afghanistan  AFG  1993
4  Afghanistan  AFG  1994

   Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized  \
0                                           0.223206
1                                           0.222454
2                                           0.221751
3                                           0.220987
4                                           0.220183

   Depressive disorders (share of population) - Sex: Both - Age: Age-standardized  \
0                                           4.996118
1                                           4.989290
2                                           4.981346
3                                           4.976958
4                                           4.977782

   Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized  \
0                                           4.713314
1                                           4.702100
2                                           4.683743
3                                           4.673549
4                                           4.670810

   Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized  \
0                                           0.703023
1                                           0.702069
2                                           0.700792
3                                           0.700087
4                                           0.699898

   Eating disorders (share of population) - Sex: Both - Age: Age-standardized
0                                           0.127700
1                                           0.123256
2                                           0.118844
3                                           0.115089
4                                           0.111815

In [ ]:
#3. ตรวจและจัดการค่าหาย
print("ค่าหายแต่ละคอลัมน์:")
print(df.isna().sum())

ค่าหายแต่ละคอลัมน์:
Entity                                                                                 0
Code                                                                                 270
Year                                                                                   0
Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized      0
Depressive disorders (share of population) - Sex: Both - Age: Age-standardized         0
Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized            0
Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized            0
Eating disorders (share of population) - Sex: Both - Age: Age-standardized             0
dtype: int64

In [ ]:
# ดูว่าแถวที่ Code หายคือพื้นที่อะไร (เป็นกลุ่มรวม ไม่ใช่ข้อมูลเสีย)
print("พื้นที่ที่ไม่มี Code:")
print(df.loc[df["Code"].isna(), "Entity"].unique())

พื้นที่ที่ไม่มี Code:
<StringArray>
[            'Africa (IHME GBD)',            'America (IHME GBD)',
               'Asia (IHME GBD)',             'Europe (IHME GBD)',
           'European Union (27)',         'High-income countries',
          'Low-income countries', 'Lower-middle-income countries',
 'Upper-middle-income countries']
Length: 9, dtype: str

In [ ]:
# เติม Unknown แทนการลบแถว
df["Code"] = df["Code"].fillna("Unknown")
print("Code ที่ยังหายหลังเติม:", df["Code"].isna().sum())

Code ที่ยังหายหลังเติม: 0

In [ ]:
#4. ตรวจข้อมูลซ้ำ
print("แถวซ้ำทั้งแถว:", df.duplicated().sum())
print("ซ้ำที่ Entity + Year:", df.duplicated(subset=["Entity", "Year"]).sum())
df = df.drop_duplicates().reset_index(drop=True)

แถวซ้ำทั้งแถว: 0
ซ้ำที่ Entity + Year: 0

In [ ]:
#5. ทำความสะอาดข้อความ และตั้งชื่อคอลัมน์ใหม่ให้สั้น
df["Entity"] = df["Entity"].str.strip()
 
long_cols = df.columns[3:]  # 5 คอลัมน์โรค (ชื่อยาว)
df = df.rename(columns={
    long_cols[0]: "Schizophrenia_pct",
    long_cols[1]: "Depressive_pct",
    long_cols[2]: "Anxiety_pct",
    long_cols[3]: "Bipolar_pct",
    long_cols[4]: "Eating_pct",
})
disease_cols = ["Schizophrenia_pct", "Depressive_pct", "Anxiety_pct",
                "Bipolar_pct", "Eating_pct"]

In [ ]:
#6. ตรวจความสมเหตุสมผลของค่า (ต้องเป็นร้อยละ 0-100 และไม่ติดลบ)
print("ค่าติดลบ:", (df[disease_cols] < 0).sum().sum())
print("ค่าเกิน 100:", (df[disease_cols] > 100).sum().sum())
print("ช่วงปี:", df["Year"].min(), "-", df["Year"].max())
print("จำนวนปีต่อพื้นที่:", df.groupby("Entity")["Year"].count().unique())

ค่าติดลบ: 0
ค่าเกิน 100: 0
ช่วงปี: 1990 - 2019
จำนวนปีต่อพื้นที่: [30]

In [ ]:
#7. แยกประเทศออกจากกลุ่มรวม (World, Asia, High-income ฯลฯ)
is_group = (df["Code"] == "Unknown") | (df["Entity"] == "World")
df["Entity_type"] = is_group.map({True: "Region/Group", False: "Country"})
print(df.groupby("Entity_type")["Entity"].nunique())

Entity_type
Country         204
Region/Group     10
Name: Entity, dtype: int64

In [ ]:
#8. ตรวจค่าผิดปกติด้วยกฎ 1.5 x IQR (เฉพาะประเทศ)
# ตรวจและนับเท่านั้น ไม่ลบ เพราะค่าสูงเป็นค่าจริงของบางประเทศ
countries = df[df["Entity_type"] == "Country"]
rows = []
for c in disease_cols:
    q1, q3 = countries[c].quantile(0.25), countries[c].quantile(0.75)
    iqr = q3 - q1
    low, high = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    n_out = ((countries[c] < low) | (countries[c] > high)).sum()
    rows.append({"โรค": c, "Q1": q1, "Q3": q3, "IQR": iqr,
                 "เส้นล่าง": low, "เส้นบน": high,
                 "จำนวนค่าผิดปกติ": n_out,
                 "สัดส่วน(%)": round(n_out / len(countries) * 100, 2)})
outlier_table = pd.DataFrame(rows).round(4)
print(outlier_table.to_string(index=False))

              โรค     Q1     Q3    IQR  เส้นล่าง  เส้นบน  จำนวนค่าผิดปกติ  สัดส่วน(%)
Schizophrenia_pct 0.2417 0.2857 0.0440    0.1757  0.3517              180        2.94
   Depressive_pct 3.0615 4.3720 1.3105    1.0958  6.3377               65        1.06
      Anxiety_pct 3.4245 4.5445 1.1200    1.7445  6.2244              334        5.46
      Bipolar_pct 0.5213 0.8575 0.3362    0.0171  1.3617               30        0.49
       Eating_pct 0.0957 0.2437 0.1481   -0.1265  0.4658              331        5.41

In [ ]:
#9. จัดเรียง ปัดทศนิยม และบันทึกไฟล์
df[disease_cols] = df[disease_cols].round(6)
df = df.sort_values(["Entity", "Year"]).reset_index(drop=True)
df = df[["Entity", "Code", "Entity_type", "Year"] + disease_cols]
 
os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
df.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig")
outlier_table.to_csv(OUTLIER_FILE, index=False, encoding="utf-8-sig")
print("บันทึกแล้ว:", OUTPUT_FILE)

บันทึกแล้ว: C:\Users\LENOVO\OneDrive - BUU\Desktop\Data\processed\Mental_cleaned.csv

In [28]:
#10. ตรวจผลลัพธ์สุดท้าย
check = pd.read_csv(OUTPUT_FILE, keep_default_na=False)
print("ขนาดหลังคลีน:", check.shape)
print("ช่องว่างที่เหลือ:", (check == "").sum().sum())
print(check["Entity_type"].value_counts())

ขนาดหลังคลีน: (6420, 9)
ช่องว่างที่เหลือ: 0
Entity_type
Country         6120
Region/Group     300
Name: count, dtype: int64

In [ ]:
#คลีนข้อมูลรายได้
import os
import pandas as pd

BASE = r"C:\Users\LENOVO\OneDrive - BUU\Desktop\Data"
INPUT_FILE = os.path.join(BASE, "raw", "OGHIST_2026_10_08.xlsx")
OUT_DIR = os.path.join(BASE, "processed")
os.makedirs(OUT_DIR, exist_ok=True)
YEAR_START, YEAR_END = 1990, 2019

# ---------- 1) เลือกชีตที่มีรหัสประเทศมากที่สุด ----------
xls = pd.ExcelFile(INPUT_FILE)
best = None
for sh in xls.sheet_names:
    tmp = pd.read_excel(INPUT_FILE, sheet_name=sh, header=None)
    n = tmp.iloc[:, 0].astype(str).str.strip().str.match(r"^[A-Z]{3}$").sum()
    print(f"ชีต '{sh}': ขนาด {tmp.shape}, แถวที่มีรหัสประเทศ = {n}")
    if best is None or n > best[0]:
        best = (n, sh, tmp)

n_codes, sheet_used, raw = best
print("\n>>> ใช้ชีต:", sheet_used, "| จำนวนประเทศ:", n_codes)
if n_codes == 0:
    raise ValueError("ไม่พบรหัสประเทศในคอลัมน์ A ของชีตไหนเลย ส่งรายชื่อชีตข้างบนมาให้ดู")

# ---------- 2) หาแถวประเทศแถวแรก และแถวปีที่อยู่เหนือมัน ----------
is_code = raw.iloc[:, 0].astype(str).str.strip().str.match(r"^[A-Z]{3}$")
first_data = is_code.idxmax()

year_row = None
for i in range(first_data - 1, -1, -1):          # ไล่ขึ้นจากแถวข้อมูล
    nums = pd.to_numeric(raw.iloc[i], errors="coerce")
    if ((nums >= 1900) & (nums <= 2100)).sum() >= 10:
        year_row = i
        break
if year_row is None:
    raise ValueError("ไม่พบแถวปีเหนือแถวข้อมูล")

print("แถวข้อมูลแรก (index):", first_data, "| แถวปี (index):", year_row)

# ---------- 3) เลือกคอลัมน์ปี 1990-2019 (ไม่สมมติว่าเริ่มที่คอลัมน์ C) ----------
yrs = pd.to_numeric(raw.iloc[year_row], errors="coerce")
keep_pos = [j for j in range(raw.shape[1])
            if pd.notna(yrs.iloc[j]) and YEAR_START <= yrs.iloc[j] <= YEAR_END]
keep_years = [int(yrs.iloc[j]) for j in keep_pos]

df = raw.iloc[first_data:, [0, 1] + keep_pos].copy()
df.columns = ["country_code", "country_name"] + keep_years

# ---------- 4) ทำความสะอาด ----------
df["country_code"] = df["country_code"].astype(str).str.strip()
df["country_name"] = df["country_name"].astype(str).str.strip()
df = df[df["country_code"].str.match(r"^[A-Z]{3}$")]
df = df.replace({"..": pd.NA, "": pd.NA})
df = df.drop_duplicates(subset="country_code").reset_index(drop=True)
for y in keep_years:
    df[y] = df[y].astype("string").str.strip()

# ---------- 5) แปลงเป็นแบบ 4 คอลัมน์ ----------
income_map = {"L": "Low income", "LM": "Lower-middle income",
              "UM": "Upper-middle income", "H": "High income"}

df_final = df.melt(id_vars=["country_code", "country_name"],
                   var_name="year", value_name="income_group")
df_final["year"] = df_final["year"].astype(int)
df_final["income_group"] = df_final["income_group"].map(income_map)

# เรียงและเลือกเฉพาะ 4 คอลัมน์
df_final = (df_final[["country_code", "country_name", "year", "income_group"]]
            .sort_values(["country_code", "year"])
            .reset_index(drop=True))

# ---------- 6) เช็กผลและบันทึก ----------
print("ขนาด:", df_final.shape)
print("ค่า missing ใน income_group:", df_final["income_group"].isna().sum())
print(df_final["income_group"].value_counts(dropna=False))
display(df_final.head(10))

out_path = os.path.join(OUT_DIR, "income_cleaned.csv")
df_final.to_csv(out_path, index=False, encoding="utf-8-sig")
print("บันทึกแล้วที่:", out_path)

ชีต 'Parameters': ขนาด (10, 2), แถวที่มีรหัสประเทศ = 0
ชีต 'Thresholds': ขนาด (44, 54), แถวที่มีรหัสประเทศ = 0
ชีต 'Country Analytical History': ขนาด (235, 41), แถวที่มีรหัสประเทศ = 223
ชีต 'Operational Category Change': ขนาด (487, 5), แถวที่มีรหัสประเทศ = 0
ชีต 'Country Indebtedness History': ขนาด (241, 18), แถวที่มีรหัสประเทศ = 212

>>> ใช้ชีต: Country Analytical History | จำนวนประเทศ: 223
แถวข้อมูลแรก (index): 6 | แถวปี (index): 5
ขนาด: (6690, 4)
ค่า missing ใน income_group: 402
income_group
High income            1824
Lower-middle income    1680
Low income             1477
Upper-middle income    1307
NaN                     402
Name: count, dtype: int64

  country_code country_name  year         income_group
0          ABW        Aruba  1990          High income
1          ABW        Aruba  1991  Upper-middle income
2          ABW        Aruba  1992  Upper-middle income
3          ABW        Aruba  1993  Upper-middle income
4          ABW        Aruba  1994          High income
5          ABW        Aruba  1995          High income
6          ABW        Aruba  1996          High income
7          ABW        Aruba  1997          High income
8          ABW        Aruba  1998          High income
9          ABW        Aruba  1999          High income

บันทึกแล้วที่: C:\Users\LENOVO\OneDrive - BUU\Desktop\Data\processed\income_cleaned.csv

In [23]:
import os   #จัดการข้อมูลรายได้
import pandas as pd

BASE = r"C:\Users\LENOVO\OneDrive - BUU\Desktop\Data"
FILE = os.path.join(BASE, "processed", "income_cleaned.csv")

df = pd.read_csv(FILE)

# ---------- 1) ขนาดและโครงสร้าง ----------
print("=== 1) ขนาดข้อมูล ===")
print(f"จำนวนแถว: {df.shape[0]:,} | จำนวนคอลัมน์: {df.shape[1]}")
print("ชื่อคอลัมน์:", list(df.columns))

print("\n=== 2) ชนิดข้อมูล ===")
print(df.dtypes)

print("\n=== 3) ตัวอย่างข้อมูล ===")
display(df.head(10))
display(df.tail(5))

# ---------- 2) ค่าว่าง ----------
print("\n=== 4) ค่าว่าง (missing) ===")
miss = df.isna().sum()
miss_pct = (miss / len(df) * 100).round(2)
display(pd.DataFrame({"missing": miss, "missing_%": miss_pct}))

# ---------- 3) ค่าซ้ำ ----------
print("\n=== 5) ค่าซ้ำ ===")
print("แถวซ้ำทั้งแถว:", df.duplicated().sum())
print("คู่ (ประเทศ, ปี) ซ้ำ:", df.duplicated(subset=["country_code", "year"]).sum())

# ---------- 4) ความครบถ้วนของปีและประเทศ ----------
print("\n=== 6) ปีและประเทศ ===")
print(f"ช่วงปี: {df['year'].min()} - {df['year'].max()} (จำนวนปีที่ไม่ซ้ำ = {df['year'].nunique()})")
print("จำนวนประเทศ (country_code):", df["country_code"].nunique())
print("จำนวนชื่อประเทศ (country_name):", df["country_name"].nunique())

expected = df["country_code"].nunique() * df["year"].nunique()
print(f"จำนวนแถวที่ควรมี (ประเทศ × ปี) = {expected:,} | ที่มีจริง = {len(df):,}")

per_country = df.groupby("country_code")["year"].nunique()
incomplete = per_country[per_country < df["year"].nunique()]
print("ประเทศที่มีปีไม่ครบ:", len(incomplete))

# ---------- 5) ค่าของกลุ่มรายได้ ----------
print("\n=== 7) การกระจายของ income_group ===")
display(df["income_group"].value_counts(dropna=False).to_frame("จำนวนแถว"))

valid = {"Low income", "Lower-middle income", "Upper-middle income", "High income"}
unexpected = set(df["income_group"].dropna().unique()) - valid
print("ค่าที่ไม่คาดคิด:", unexpected if unexpected else "ไม่มี")

# ---------- 6) ประเทศที่มีค่าว่างมากที่สุด ----------
print("\n=== 8) ประเทศที่มีปีไม่มีข้อมูลมากที่สุด (Top 10) ===")
na_by_country = (df[df["income_group"].isna()]
                 .groupby(["country_code", "country_name"]).size()
                 .sort_values(ascending=False).head(10))
display(na_by_country.to_frame("ปีที่ไม่มีข้อมูล"))

# ---------- 7) ตรวจว่า 1 รหัสตรงกับ 1 ชื่อ ----------
names_per_code = df.groupby("country_code")["country_name"].nunique()
print("\nรหัสประเทศที่มีมากกว่า 1 ชื่อ:", int((names_per_code > 1).sum()))

=== 1) ขนาดข้อมูล ===
จำนวนแถว: 6,690 | จำนวนคอลัมน์: 4
ชื่อคอลัมน์: ['country_code', 'country_name', 'year', 'income_group']

=== 2) ชนิดข้อมูล ===
country_code      str
country_name      str
year            int64
income_group      str
dtype: object

=== 3) ตัวอย่างข้อมูล ===

  country_code country_name  year         income_group
0          ABW        Aruba  1990          High income
1          ABW        Aruba  1991  Upper-middle income
2          ABW        Aruba  1992  Upper-middle income
3          ABW        Aruba  1993  Upper-middle income
4          ABW        Aruba  1994          High income
5          ABW        Aruba  1995          High income
6          ABW        Aruba  1996          High income
7          ABW        Aruba  1997          High income
8          ABW        Aruba  1998          High income
9          ABW        Aruba  1999          High income

     country_code country_name  year         income_group
6685          ZWE     Zimbabwe  2015           Low income
6686          ZWE     Zimbabwe  2016           Low income
6687          ZWE     Zimbabwe  2017           Low income
6688          ZWE     Zimbabwe  2018  Lower-middle income
6689          ZWE     Zimbabwe  2019  Lower-middle income

=== 4) ค่าว่าง (missing) ===

              missing  missing_%
country_code        0       0.00
country_name        0       0.00
year                0       0.00
income_group      402       6.01

=== 5) ค่าซ้ำ ===
แถวซ้ำทั้งแถว: 0
คู่ (ประเทศ, ปี) ซ้ำ: 0

=== 6) ปีและประเทศ ===
ช่วงปี: 1990 - 2019 (จำนวนปีที่ไม่ซ้ำ = 30)
จำนวนประเทศ (country_code): 223
จำนวนชื่อประเทศ (country_name): 223
จำนวนแถวที่ควรมี (ประเทศ × ปี) = 6,690 | ที่มีจริง = 6,690
ประเทศที่มีปีไม่ครบ: 0

=== 7) การกระจายของ income_group ===

                     จำนวนแถว
income_group
High income              1824
Lower-middle income      1680
Low income               1477
Upper-middle income      1307
NaN                       402

ค่าที่ไม่คาดคิด: ไม่มี

=== 8) ประเทศที่มีปีไม่มีข้อมูลมากที่สุด (Top 10) ===

                                        ปีที่ไม่มีข้อมูล
country_code country_name
SUN          USSR (former)                            29
CSK          Czechoslovakia (former)                  28
NRU          Naoero                                   25
VGB          British Virgin Islands                   25
SSD          South Sudan                              21
CUW          Curaçao                                  20
SXM          Sint Maarten (Dutch part)                20
MAF          St. Martin (French part)                 20
GIB          Gibraltar                                19
TUV          Tuvalu                                   19

รหัสประเทศที่มีมากกว่า 1 ชื่อ: 0

In [24]:
#สเต็ปที่2 mergeข้อมูลเข้าด้วยกันจากข้อมูลสุขภาพจิตที่คลีนแล้ว
import os
import pandas as pd

BASE = r"C:\Users\LENOVO\OneDrive - BUU\Desktop\Data"
PROC = os.path.join(BASE, "processed")

# 1) โหลดข้อมูลสุขภาพจิตที่คลีนแล้ว (หาไฟล์ Mental_cleaned เองโดยไม่ต้องรู้นามสกุล)
mental_file = next(
    (os.path.join(PROC, f) for f in os.listdir(PROC) if f.lower().startswith("mental_cleaned")),
    None,
)
if mental_file is None:
    raise FileNotFoundError(f"ไม่พบ Mental_cleaned ใน {PROC}\nไฟล์ที่มี: {os.listdir(PROC)}")

print("ใช้ไฟล์:", mental_file)
if mental_file.lower().endswith((".xlsx", ".xls")):
    df_mental = pd.read_excel(mental_file)
else:
    df_mental = pd.read_csv(mental_file)

# 2) โหลดข้อมูลรายได้ที่คลีนแล้ว
df_income = pd.read_csv(os.path.join(PROC, "income_cleaned.csv"))

# 3) ตรวจชื่อคอลัมน์และขนาด
print("\nคอลัมน์ของ df_mental:", df_mental.columns.tolist())
print("คอลัมน์ของ df_income:", df_income.columns.tolist())
print("\nขนาด df_mental:", df_mental.shape, "| ขนาด df_income:", df_income.shape)
display(df_mental.head())

ใช้ไฟล์: C:\Users\LENOVO\OneDrive - BUU\Desktop\Data\processed\Mental_cleaned.csv

คอลัมน์ของ df_mental: ['Entity', 'Code', 'Entity_type', 'Year', 'Schizophrenia_pct', 'Depressive_pct', 'Anxiety_pct', 'Bipolar_pct', 'Eating_pct']
คอลัมน์ของ df_income: ['country_code', 'country_name', 'year', 'income_group']

ขนาด df_mental: (6420, 9) | ขนาด df_income: (6690, 4)

,Entity,Code,Entity_type,Year,Schizophrenia_pct,Depressive_pct,Anxiety_pct,Bipolar_pct,Eating_pct
0,Afghanistan,AFG,Country,1990,0.223206,4.996118,4.713314,0.703023,0.127700
1,Afghanistan,AFG,Country,1991,0.222454,4.989290,4.702100,0.702069,0.123256
2,Afghanistan,AFG,Country,1992,0.221751,4.981346,4.683743,0.700792,0.118844
3,Afghanistan,AFG,Country,1993,0.220987,4.976958,4.673549,0.700087,0.115089
4,Afghanistan,AFG,Country,1994,0.220183,4.977782,4.670810,0.699898,0.111815

In [25]:
# 1) เปลี่ยนชื่อคอลัมน์ให้ตรงกับไฟล์รายได้ และตั้งชื่อโรคให้สั้น
df_mental = df_mental.rename(columns={
    "Entity": "country_name_mental",
    "Code": "country_code",
    "Year": "year",
    "Schizophrenia_pct": "Schizophrenia",
    "Depressive_pct": "Depressive",
    "Anxiety_pct": "Anxiety",
    "Bipolar_pct": "Bipolar",
    "Eating_pct": "Eating",
})

# 2) เก็บเฉพาะแถวที่เป็นประเทศ และปี 1990-2019
print("ชนิด Entity_type:", df_mental["Entity_type"].unique())
df_mental = df_mental[df_mental["Entity_type"] == "Country"]
df_mental = df_mental[df_mental["year"].between(1990, 2019)]
df_mental = df_mental.dropna(subset=["country_code"])

# 3) Merge ด้วย country_code + year
df = df_mental.merge(
    df_income[["country_code", "year", "income_group"]],
    on=["country_code", "year"],
    how="left",            # ใช้ left ก่อนเพื่อดูว่ามีแถวไหนไม่มีรายได้
    indicator=True,
)

# 4) สรุปผลก่อนตัด (เก็บไว้เขียนรายงาน)
print("แถวหลัง merge:", len(df))
print("แถวที่ไม่มีข้อมูลรายได้:", df["income_group"].isna().sum())
print("ประเทศที่ไม่มีรายได้เลย:",
      sorted(df.groupby("country_code")["income_group"]
               .apply(lambda s: s.isna().all()).loc[lambda s: s].index.tolist()))

# 5) ตัดแถวที่ไม่มีกลุ่มรายได้
df = df.dropna(subset=["income_group"]).drop(columns="_merge").reset_index(drop=True)

# 6) ตรวจผลสุดท้าย
print("\n=== ผลหลังตัด ===")
print("ขนาด:", df.shape)
print("จำนวนประเทศ:", df["country_code"].nunique())
print("ช่วงปี:", df["year"].min(), "-", df["year"].max())
print("ค่า missing ต่อคอลัมน์:")
print(df.isna().sum())
print("\nการกระจายกลุ่มรายได้:")
print(df["income_group"].value_counts())
display(df.head())

# 7) บันทึก
out = os.path.join(PROC, "mental_income_merged.csv")
df.to_csv(out, index=False, encoding="utf-8-sig")
print("\nบันทึกแล้วที่:", out)

ชนิด Entity_type: <StringArray>
['Country', 'Region/Group']
Length: 2, dtype: str
แถวหลัง merge: 6120
แถวที่ไม่มีข้อมูลรายได้: 252
ประเทศที่ไม่มีรายได้เลย: ['COK', 'NIU', 'TKL']

=== ผลหลังตัด ===
ขนาด: (5868, 10)
จำนวนประเทศ: 201
ช่วงปี: 1990 - 2019
ค่า missing ต่อคอลัมน์:
country_name_mental    0
country_code           0
Entity_type            0
year                   0
Schizophrenia          0
Depressive             0
Anxiety                0
Bipolar                0
Eating                 0
income_group           0
dtype: int64

การกระจายกลุ่มรายได้:
income_group
Lower-middle income    1656
High income            1485
Low income             1477
Upper-middle income    1250
Name: count, dtype: int64

,country_name_mental,country_code,Entity_type,year,Schizophrenia,Depressive,Anxiety,Bipolar,Eating,income_group
0,Afghanistan,AFG,Country,1990,0.223206,4.996118,4.713314,0.703023,0.127700,Low income
1,Afghanistan,AFG,Country,1991,0.222454,4.989290,4.702100,0.702069,0.123256,Low income
2,Afghanistan,AFG,Country,1992,0.221751,4.981346,4.683743,0.700792,0.118844,Low income
3,Afghanistan,AFG,Country,1993,0.220987,4.976958,4.673549,0.700087,0.115089,Low income
4,Afghanistan,AFG,Country,1994,0.220183,4.977782,4.670810,0.699898,0.111815,Low income

บันทึกแล้วที่: C:\Users\LENOVO\OneDrive - BUU\Desktop\Data\processed\mental_income_merged.csv

In [26]:
import os, pandas as pd
PROC = r"C:\Users\LENOVO\OneDrive - BUU\Desktop\Data\processed"
df = pd.read_csv(os.path.join(PROC, "mental_income_merged.csv"))

diseases = ["Schizophrenia", "Depressive", "Anxiety", "Bipolar", "Eating"]

print("1) ขนาด:", df.shape, "| ประเทศ:", df["country_code"].nunique(),
      "| ปี:", df["year"].min(), "-", df["year"].max())

print("\n2) กลุ่มรายได้ครบ 4 กลุ่มไหม:")
print(df["income_group"].value_counts())

print("\n3) Missing ต่อคอลัมน์:")
print(df.isna().sum())

print("\n4) แถวซ้ำ (ประเทศ, ปี):", df.duplicated(subset=["country_code", "year"]).sum())

print("\n5) สถิติของแต่ละโรค (ดูค่าติดลบ/ผิดปกติ):")
display(df[diseases].describe().round(3))

print("\n6) ประเทศที่ปีไม่ครบ 30 ปี:")
cnt = df.groupby("country_code")["year"].nunique()
print((cnt < 30).sum(), "ประเทศ")
display(cnt[cnt < 30].sort_values().head(15))

1) ขนาด: (5868, 10) | ประเทศ: 201 | ปี: 1990 - 2019

2) กลุ่มรายได้ครบ 4 กลุ่มไหม:
income_group
Lower-middle income    1656
High income            1485
Low income             1477
Upper-middle income    1250
Name: count, dtype: int64

3) Missing ต่อคอลัมน์:
country_name_mental    0
country_code           0
Entity_type            0
year                   0
Schizophrenia          0
Depressive             0
Anxiety                0
Bipolar                0
Eating                 0
income_group           0
dtype: int64

4) แถวซ้ำ (ประเทศ, ปี): 0

5) สถิติของแต่ละโรค (ดูค่าติดลบ/ผิดปกติ):

       Schizophrenia  Depressive   Anxiety   Bipolar    Eating
count       5868.000    5868.000  5868.000  5868.000  5868.000
mean           0.265       3.785     4.106     0.649     0.198
std            0.040       0.949     1.079     0.233     0.140
min            0.188       1.522     1.880     0.182     0.045
25%            0.240       3.054     3.417     0.524     0.096
50%            0.272       3.682     3.941     0.582     0.148
75%            0.285       4.388     4.566     0.871     0.252
max            0.462       7.646     8.625     1.507     1.032

6) ประเทศที่ปีไม่ครบ 30 ปี:
35 ประเทศ

country_code
NRU     5
SSD     9
TUV    11
MNE    14
SRB    14
TLS    19
SMR    23
PLW    24
PSE    26
MCO    26
ERI    28
BIH    28
HRV    28
MNP    28
SVN    28
Name: year, dtype: int64

In [ ]:
#ข้อมูลพร้อมใช้ในการคำนวณแล้ว